#!/bin/bash

# Funzione per rimuovere i tag VTT e altri indesiderati
remove_tags() {
    sed -e 's/<\/c>//g' \
        -e 's/<c(\.color\w\+)\?>//g' \
        -e 's/<[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\.[0-9]\{3\}>//g' \
        -e 's/\([0-9]\{2\}:[0-9]\{2\}\):[0-9]\{2\}\.[0-9]\{3\} --> .* align:start position:0%/\1/' \
        -e 's/\[Applause\]//g' \
        -e 's/\[Music\]//g' \
        -e '/^\s*$/d'
}

# Funzione per rimuovere l'header del file VTT
remove_header() {
    awk '/##|Language: en/{flag=1; next} flag'
}

# Funzione per rimuovere i tag <c>
remove_c_tags() {
    sed -e 's/<c>//g'
}

# Funzione per rimuovere righe duplicate consecutive
remove_consecutive_duplicates() {
    awk '!seen[$0]++'
}

# Funzione per rimuovere righe di timestamp
remove_timestamps() {
    sed -e '/^[0-9]\{2\}:[0-9]\{2\}$/d'
}

# Funzione per unire le righe corte
merge_short_lines() {
    awk '{
        if ($0 ~ /^[0-9]{2}:[0-9]{2}$/ || $0 == "") {
            if (length(buffer)) {
                print buffer;
                buffer = "";
            }
            print;
        } else {
            if (length(buffer $0) < 80) {
                buffer = (buffer ? buffer " " : "") $0;
            } else {
                if (length(buffer)) print buffer;
                buffer = $0;
            }
        }
    } END { if (length(buffer)) print buffer }'
}

# Funzione principale
main() {
    vtt_file_name="$1"
    txt_name="${vtt_file_name%.vtt}.txt"

    # Leggi il file, esegui i passaggi e salva l'output
    cat "$vtt_file_name" |
        remove_tags |                     # Rimozione tag
        remove_header |                   # Rimozione dell'header
        remove_c_tags |                   # Rimozione tag <c>
        remove_consecutive_duplicates |   # Rimozione dei duplicati
        remove_timestamps |               # Rimozione dei timestamp
        merge_short_lines > "$txt_name"  # Unione delle righe corte
}

# Verifica che un file sia stato fornito come argomento
if [ -z "$1" ]; then
    echo "Usage: $0 <vtt_file>"
    exit 1
fi

main "$1"
